export const BASE_URL = 'https://donatbook-apis.herokuapp.com/api';

export const GET_USER_COUNTRY_REQUEST = 'GET_USER_COUNTRY_REQUEST';
export const GET_USER_COUNTRY_SUCCESS = 'GET_USER_COUNTRY_SUCCESS';
export const GET_USER_COUNTRY_ERROR = 'GET_USER_COUNTRY_ERROR';

export const GET_USER_CITY_REQUEST = 'GET_USER_CITY_REQUEST';
export const GET_USER_CITY_SUCCESS = 'GET_USER_CITY_SUCCESS';
export const GET_USER_CITY_ERROR = 'GET_USER_CITY_ERROR';

export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_ERROR = 'USER_SIGNUP_ERROR';

export const USER_OTP_DETAIL_REQUEST = 'USER_OTP_DETAIL_REQUEST';
export const USER_OTP_DETAIL_SUCCESS = 'USER_OTP_DETAIL_SUCCESS';
export const USER_OTP_DETAIL_ERROR = 'USER_OTP_DETAIL_ERROR';

export const RESEND_OTP_DETAIL_REQUEST = 'RESEND_OTP_DETAIL_REQUEST';
export const RESEND_OTP_DETAIL_SUCCESS = 'RESEND_OTP_DETAIL_SUCCESS';
export const RESEND_OTP_DETAIL_ERROR = 'RESEND_OTP_DETAIL_ERROR';
